"""Deterministic final-submission assembly.

The assembly stage combines:

* a baseline Track-1/Track-2 prediction table,
* per-item model source slices selected by leave-one-subject-out CV, and
* a deterministic Track-1 clinical-consistency source generated by
  ``src/cv4chl/clinical_consistency.py`` (patient-agnostic rules).

Reviewer reproduction uses committed release artifacts plus the
explicitly generated clinical-consistency CSV. The same inputs produce
the byte-exact ``final_submission.csv`` file.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


FINAL_NAME = "final_submission.csv"

ITEM_COLS = [f"L{i}" for i in range(1, 18)] + [f"R{i}" for i in range(1, 18)]

BASELINE_REF = Path("submissions/reference/xgb_baseline.csv")
TRACK2_REF = Path("submissions/intermediate/track2_classifier_output.csv")
CLINICAL_CONSISTENCY_REF = Path("submissions/item_sources/clinical_consistency_track1.csv")

FRESH_BASELINE = Path("5_outputs/submissions/xgb_baseline.csv")
FRESH_TRACK2 = Path("5_outputs/submissions/track2_clinical_predictions.csv")
FRESH_CLINICAL_CONSISTENCY = Path("5_outputs/submissions/clinical_consistency_track1.csv")

ITEM_SOURCE_SPECS: dict[str, tuple[Path, tuple[str, ...], tuple[Path, ...]]] = {
    "item03": (
        Path("submissions/item_sources/item03_evgs_rules.csv"),
        ("L3", "R3"),
        (Path("5_outputs/submissions/evgs_rules_individual_item_03.csv"),),
    ),
    "item05": (
        Path("submissions/item_sources/item05_classifier_ensemble.csv"),
        ("L5", "R5"),
        (Path("5_outputs/submissions/item05_classifier_ensemble_full.csv"),),
    ),
    "item09": (
        Path("submissions/item_sources/item09_evgs_rules.csv"),
        ("L9", "R9"),
        (Path("5_outputs/submissions/evgs_rules_individual_item_09.csv"),),
    ),
    "item11": (
        Path("submissions/item_sources/item11_evgs_rules.csv"),
        ("L11", "R11"),
        (Path("5_outputs/submissions/evgs_rules_individual_item_11.csv"),),
    ),
    "item12": (
        Path("submissions/item_sources/item12_model_diversity.csv"),
        ("R12",),
        (Path("5_outputs/submissions/item12_model_diversity.csv"),),
    ),
    "item14": (
        Path("submissions/item_sources/item14_tcn.csv"),
        ("L14", "R14"),
        (Path("5_outputs/submissions/tcn_item14/item14_tcn.csv"),),
    ),
    "item15": (
        Path("submissions/item_sources/item15_evgs_rules.csv"),
        ("L15", "R15"),
        (Path("5_outputs/submissions/evgs_rules_individual_item_15.csv"),),
    ),
    "item16": (
        Path("submissions/item_sources/item16_evgs_rules.csv"),
        ("L16", "R16"),
        (Path("5_outputs/submissions/evgs_rules_individual_item_16.csv"),),
    ),
    "item17": (
        Path("submissions/item_sources/item17_evgs_rules.csv"),
        ("L17", "R17"),
        (Path("5_outputs/submissions/evgs_rules_individual_item_17.csv"),),
    ),
}

# Maps each item-source key to the training notebook that produces its
# canonical fresh artifact. Used to surface actionable error messages
# when full-retrain assembly is missing an input.
ITEM_SOURCE_NOTEBOOK: dict[str, str] = {
    "item03": "02_train_pipeline/CV4CHL_04_train_evgs_rule_sources.ipynb",
    "item05": "02_train_pipeline/CV4CHL_06_train_item05_classifier_ensemble.ipynb",
    "item09": "02_train_pipeline/CV4CHL_04_train_evgs_rule_sources.ipynb",
    "item11": "02_train_pipeline/CV4CHL_04_train_evgs_rule_sources.ipynb",
    "item12": "02_train_pipeline/CV4CHL_05_train_model_diversity_item12.ipynb",
    "item14": "02_train_pipeline/CV4CHL_07_train_tcn_item14.ipynb",
    "item15": "02_train_pipeline/CV4CHL_04_train_evgs_rule_sources.ipynb",
    "item16": "02_train_pipeline/CV4CHL_04_train_evgs_rule_sources.ipynb",
    "item17": "02_train_pipeline/CV4CHL_04_train_evgs_rule_sources.ipynb",
}


def _first_existing(root: Path, paths: tuple[Path, ...] | list[Path],
                    hint: str | None = None) -> Path:
    for rel in paths:
        candidate = root / rel
        if candidate.exists():
            return candidate
    tried = "\n".join(f"  - {root / p}" for p in paths)
    msg = f"required assembly input not found; tried:\n{tried}"
    if hint:
        msg += f"\n{hint}"
    raise FileNotFoundError(msg)


def _read_source(root: Path, reference: Path, columns: tuple[str, ...],
                 fresh: tuple[Path, ...], use_runtime: bool,
                 stage_hint: str | None = None) -> pd.DataFrame:
    # Full-retrain mode (use_runtime=True) requires the freshly produced
    # artifact and fails fast if it is missing, ensuring the final CSV
    # genuinely depends on the retrain rather than a stale committed copy.
    if use_runtime:
        candidates: tuple[Path, ...] | list[Path] = fresh
        hint = (
            f"Full-retrain assembly expects the freshly produced artifact above. "
            f"Re-run the responsible training notebook ({stage_hint}) before assembly, "
            f"or pass --skip-train to use the committed release artifact "
            f"({reference})."
        ) if stage_hint else None
    else:
        candidates = [reference]
        hint = None
    path = _first_existing(root, candidates, hint=hint)
    df = pd.read_csv(path)
    required = {"ID", *columns}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"{path} is missing required columns: {sorted(missing)}")
    return df.loc[:, ["ID", *columns]].copy()


def _overlay_columns(base: pd.DataFrame, source: pd.DataFrame,
                     columns: tuple[str, ...]) -> None:
    t1_ids = base.loc[base["ID"].str.startswith("track1"), "ID"]
    source = source.set_index("ID")
    for col in columns:
        base.loc[base["ID"].isin(t1_ids), col] = source.loc[t1_ids, col].astype(int).values


def _resolve_path(root: Path, path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else root / p


def assemble_final(
    repo_root: str | Path,
    use_runtime: bool = True,
    clinical_source_path: str | Path | None = None,
) -> pd.DataFrame:
    """Assemble the final prediction table.

    By default, freshly generated runtime outputs under ``5_outputs/`` take
    precedence when present. Set ``use_runtime=False`` for reviewer
    reproduction from the committed release artifacts only.
    """
    root = Path(repo_root)

    if use_runtime:
        track2_path = _first_existing(
            root, [FRESH_TRACK2],
            hint="Run notebook 02_train_pipeline/CV4CHL_03_train_track2_clinical_classifier.ipynb, "
                 "or pass --skip-train to use the committed release artifact.",
        )
        baseline_path = _first_existing(
            root, [FRESH_BASELINE],
            hint="Run notebook 02_train_pipeline/CV4CHL_02_train_xgb_baseline.ipynb, "
                 "or pass --skip-train to use the committed release artifact.",
        )
    else:
        track2_path = _first_existing(root, [TRACK2_REF])
        baseline_path = _first_existing(root, [BASELINE_REF])
    base = pd.read_csv(track2_path)
    baseline = pd.read_csv(baseline_path)

    t1_mask = base["ID"].str.startswith("track1")
    # ID-based baseline overlay (mirrors src/cv4chl/ml_merge.py): looking up
    # by ID makes the merge robust to row order and surfaces missing IDs
    # explicitly (a positional `.values` overlay would silently mismerge if
    # baseline.csv ever got resorted).
    baseline_indexed = baseline.set_index("ID")
    t1_ids = base.loc[t1_mask, "ID"]
    missing_baseline_ids = set(t1_ids) - set(baseline_indexed.index)
    if missing_baseline_ids:
        raise ValueError(
            f"baseline CSV {baseline_path} is missing Track-1 IDs from the "
            f"track2 base table: {sorted(missing_baseline_ids)}"
        )
    base.loc[t1_mask, ITEM_COLS] = (
        baseline_indexed.loc[t1_ids, ITEM_COLS].astype(int).values
    )
    # Track-1 Total is recomputed once at the end after every overlay; computing
    # it here would be immediately invalidated by the per-item and clinical
    # overlays below.

    for key, (reference, columns, fresh) in ITEM_SOURCE_SPECS.items():
        source = _read_source(
            root, reference, columns, fresh, use_runtime,
            stage_hint=ITEM_SOURCE_NOTEBOOK.get(key),
        )
        _overlay_columns(base, source, columns)

    if clinical_source_path is not None:
        clinical_path = _resolve_path(root, clinical_source_path)
        if not clinical_path.exists():
            raise FileNotFoundError(f"clinical consistency source not found: {clinical_path}")
    elif use_runtime:
        clinical_path = _first_existing(
            root, [FRESH_CLINICAL_CONSISTENCY],
            hint="Run reproduce.py stage `clinical_consistency` (or full pipeline) "
                 "to produce this artifact, or pass --skip-train to use the committed release artifact.",
        )
    else:
        clinical_path = _first_existing(root, [CLINICAL_CONSISTENCY_REF])
    clinical = pd.read_csv(clinical_path)
    required = {"ID", *ITEM_COLS}
    missing_cols = required - set(clinical.columns)
    if missing_cols:
        raise ValueError(f"{clinical_path} is missing required columns: {sorted(missing_cols)}")
    clinical = clinical.set_index("ID")
    t1_ids = base.loc[t1_mask, "ID"]
    missing_ids = set(t1_ids) - set(clinical.index)
    if missing_ids:
        raise ValueError(f"{clinical_path} is missing Track-1 rows: {sorted(missing_ids)}")
    base.loc[t1_mask, ITEM_COLS] = clinical.loc[t1_ids, ITEM_COLS].astype(int).values

    base.loc[t1_mask, "Total"] = base.loc[t1_mask, ITEM_COLS].sum(axis=1).astype(int)
    return base


def write_final(repo_root: str | Path,
                output: str | Path | None = None,
                use_runtime: bool = True,
                clinical_source_path: str | Path | None = None) -> Path:
    """Assemble and write the final CSV using CRLF line endings."""
    root = Path(repo_root)
    out_path = Path(output) if output else root / "submissions" / "final" / FINAL_NAME
    out_path.parent.mkdir(parents=True, exist_ok=True)
    df = assemble_final(root, use_runtime=use_runtime,
                        clinical_source_path=clinical_source_path)
    df.to_csv(out_path, index=False, lineterminator="\r\n")
    return out_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--clinical-source", type=Path, default=None,
                        help="Use this generated clinical-consistency CSV for Track-1.")
    parser.add_argument("--release-artifacts", action="store_true",
                        help="Ignore 5_outputs/ and assemble from committed release artifacts only.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    out_path = write_final(args.repo_root, args.output,
                           use_runtime=not args.release_artifacts,
                           clinical_source_path=args.clinical_source)
    print(f"final submission written: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
